
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver               #配置oracle驱动类
    url: jdbc:mysql://localhost:3306/springBootBlog?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false&autoReconnect=true             #配置数据库连接地址
    username: root                                         #配置数据库连接用户名
    password: 123456                                         #配置数据库连接用户密码
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  jpa:
    show-sql: true

  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode:  HTML5
    cache: false