spring:
  mail:
    host: smtp.f5tv.com
    username: springbootblog@f5tv.com
    password: ll.201520111
    default-encoding: utf-8
    port: 465
  resources:
    static-locations: classpath:/
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode:  HTML5