spring:
  mail:
    host: smtp.f5tv.com
    username: xxx@xxx.com
    password: xxx
    default-encoding: utf-8
    port: 465
  resources:
    static-locations: classpath:/
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode:  HTML5
